version: "3.2"
services:
  db:
    restart: always
    image: postgres:10.6
    ports:
      - 2345:5432
    environment:
      - POSTGRES_USER=sinatra
      - POSTGRES_PASSWORD=sinatra
    volumes:
      - ./bt_data:/var/lib/postgresql/data
  web:
    build: ./web
    ports:
      - "9876:5000"
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: sinatra
      DATABASE_USER: sinatra
      DATABASE_PASSWORD: sinatra
      DATABASE_PORT: 5432
    volumes:
      - ./web:/web
    tty: true
    depends_on:
      - db
volumes:
  bt_data:
    external: true
