version: '3'

services:
  db:
    image: postgres:11.1
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_PASSWORD=aibiao118
      - POSTGRES_USER=gzswar
    volumes:
      - ./pg_db:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - 8080:8080
    environment:
      - POSTGRES_ROOT_PASSWORD=aibiao118
      - POSTGRES_ROOT_USER=gzswar
      - DATABASE_HOST=db
    volumes:
      - .:/BiaoTeach
    tty: true
    depends_on:
      - db
      
