version: "3"
services:
  db:
    restart: always
    image: postgres:10.6
    ports:
      - 2345:5432
    environment:
      - POSTGRES_USER=sinatra
      - POSTGRES_PASSWORD=sinatra
    volumes:
      - ./web/bt_data:/var/lib/postgres
  web:
    build: ./web
    ports:
      - "9876:5000"
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: sinatra
      DATABASE_USER: sinatra
      DATABASE_PASSWORD: sinatra
      DATABASE_PORT: 5432
    volumes:
      - ./web:/web
    working_dir: /web
    command: bash -c "foreman start"
volumes:
  bt_data:
    external: true
