source 'https://rubygems.org'

gem 'puma', '3.12.0'
gem 'sinatra', '2.0.5'
gem "sequel", "=5.18.0"
gem "sequel_pg", "=1.12.0", :require => 'sequel'
gem "pry", "0.12.2 "
gem "graphql", "=1.6.0"

group :development do
  gem 'dotenv', '2.5.0'
  gem 'foreman', '0.85.0'
end